import * as Joi from 'joi';

export const ConfigValidationSchema = Joi.object({
  DATABASE_URL: Joi.string().required(),
  JWT_ACCESS_SECRET: Joi.string().required(),
  JWT_REFRESH_SECRET: Joi.string().required(),
  JWT_ACCESS_EXPIRES_IN: Joi.string().default('15m'),
  JWT_REFRESH_EXPIRES_IN: Joi.string().default('7d'),
  ADMIN_API_KEY: Joi.string().required(),
  MAIL_HOST: Joi.string().required(),
  MAIL_PORT: Joi.number().required(),
  MAIL_SECURE: Joi.boolean().default(false),
  MAIL_USER: Joi.string().required(),
  MAIL_PASS: Joi.string().required(),
  MAIL_FROM: Joi.string().email().required(),
  MAIL_TO: Joi.string().email().required(),
  WEATHER_API_KEY: Joi.string().required(),
  WEATHER_API_BASE_URL: Joi.string().required(),
  PAYMENT_BANK_BIN: Joi.string().required(),
  PAYMENT_BANK_ACCOUNT_NO: Joi.string().required(),
  PAYMENT_BANK_ACCOUNT_NAME: Joi.string().required(),
  DEFAULT_CUSTOMER_PASSWORD: Joi.string().optional(), // CHANGED: optional stub password
  TEMP_PASSWORD_ENC_KEY: Joi.string().required(), // CHANGED: AES-GCM key for temp password
  PUSH_MODE: Joi.string().valid('stub', 'fcm').default('stub'),
  ENABLE_REALTIME: Joi.boolean().default(false),
  ENABLE_SCHEDULE_REMINDER: Joi.boolean().default(false),
  SCHEDULE_REMINDER_DAYS: Joi.number().default(7),
  SCHEDULE_REMINDER_HOUR: Joi.number().default(8),
  ENABLE_LOAN_REMINDER: Joi.boolean().default(false),
  LOAN_REMINDER_DAYS: Joi.number().default(7),
  LOAN_REMINDER_HOUR: Joi.number().default(8),
  FPT_TTS_API_KEY: Joi.string().optional(),
  FPT_TTS_VOICE: Joi.string().default('banmai'),
  FPT_TTS_SPEED: Joi.string().default('0'),
  FPT_TTS_FORMAT: Joi.string().default('mp3'),
  CONTACTS_BY_BRANCH_JSON: Joi.string().optional(),
});
